# Generated by Django 3.2.4 on 2021-10-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='thread_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
