# Generated by Django 3.2.4 on 2021-10-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatmodel_thread_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
